apiVersion: v1
kind: Service
metadata:
  labels:
    chart: nodejs-demo-0.1.0
  name: nodejs-demo
  namespace: default
spec:
  ports:
  - name: node
    nodePort: 32068
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nodejs-demo
  sessionAffinity: None
  type: LoadBalancer
