# A dummy service to make this usable with flux
apiVersion: v1
kind: Service
metadata:
  labels:
    name: load-test
  name: load-test
  namespace: default
spec:
  ports:
    - name: dummy
      port: 65535
