apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: load-test
  name: load-test
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: docker.io/errordeveloper/prom-nodejs-demo-load-test:slow
        name: load-test
        ports:
        - name: dummy
          containerPort: 65535
